use serde_json::{json, Value};
use std::io::Write;
use std::process::{Command, Stdio};

fn helper_binary() -> String {
    std::env::var("CARGO_BIN_EXE_tunnelforge-core").unwrap_or_else(|_| {
        let mut path = std::env::current_exe().unwrap();
        path.pop();
        if path.ends_with("deps") {
            path.pop();
        }
        path.push(if cfg!(windows) {
            "tunnelforge-core.exe"
        } else {
            "tunnelforge-core"
        });
        path.to_string_lossy().to_string()
    })
}

fn run_helper(request: Value) -> Vec<Value> {
    run_helper_lines(&format!("{request}\n"))
}

fn run_helper_lines(input: &str) -> Vec<Value> {
    let output = run_helper_output(input);
    String::from_utf8(output)
        .unwrap()
        .lines()
        .map(|line| serde_json::from_str::<Value>(line).unwrap())
        .collect()
}

fn run_helper_output(input: &str) -> Vec<u8> {
    let mut child = Command::new(helper_binary())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    {
        let stdin = child.stdin.as_mut().unwrap();
        write!(stdin, "{input}").unwrap();
    }
    let output = child.wait_with_output().unwrap();
    assert!(output.status.success());
    output.stdout
}

fn run_helper_with_closed_stdout(input: &str) -> std::process::Output {
    let mut child = Command::new(helper_binary())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    drop(child.stdout.take());
    {
        let mut stdin = child.stdin.take().unwrap();
        write!(stdin, "{input}").unwrap();
    }
    child.wait_with_output().unwrap()
}

#[test]
fn helper_binary_accepts_jsonl_and_emits_result() {
    let events = run_helper(json!({
        "command": "plan",
        "request_id": "cli-1",
        "payload": {
            "source_engine": "mysql",
            "target_engine": "postgresql",
            "schema": {
                "tables": [{
                    "name": "users",
                    "columns": [{
                        "name": "id",
                        "type": "int(11) auto_increment",
                        "nullable": false,
                        "primary_key": true
                    }]
                }]
            }
        }
    }));

    let result = events
        .iter()
        .find(|event| event.get("event") == Some(&json!("result")))
        .unwrap();
    assert_eq!(result["request_id"], "cli-1");
    assert_eq!(result["command"], "plan");
    assert_eq!(result["success"], true);
    assert_eq!(
        result["plan"]["ddl"][0],
        "CREATE TABLE \"users\" (\n  \"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  PRIMARY KEY (\"id\")\n);"
    );
}

fn assert_protocol_error(event: &Value, request_id: Value) {
    assert_eq!(event["event"], "error");
    assert_eq!(event["request_id"], request_id);
    assert!(event.get("command").is_some());
    assert!(matches!(event["code"].as_str(), Some(value) if !value.is_empty()));
    assert!(matches!(event["message"].as_str(), Some(value) if !value.is_empty()));
}

#[test]
fn helper_binary_negotiates_process_contract() {
    let events = run_helper(json!({
        "command": "service.hello",
        "request_id": "cli-hello-1",
        "payload": {}
    }));

    assert_eq!(events.len(), 1);
    let result = &events[0];
    assert_eq!(result["request_id"], "cli-hello-1");
    assert_eq!(result["protocol_version"], 1);
    assert_eq!(result["process_version"], 1);
    assert_eq!(
        result["process_capabilities"],
        json!([
            "request.deadline",
            "request.strict_id",
            "process.generation",
            "mutation.outcome_indeterminate"
        ])
    );
    assert_eq!(result["max_jsonl_frame_bytes"], 1_048_576);
    assert_eq!(result["max_assembled_event_bytes"], 64 * 1024 * 1024);
    assert_eq!(result["max_assembled_event_chunks"], 4_096);
    assert_eq!(result["max_assembled_event_nodes"], 65_536);
    assert_eq!(result["max_assembled_event_depth"], 128);
}

#[test]
fn helper_binary_emits_structured_unknown_command_error() {
    let events = run_helper(json!({
        "command": "unknown.command",
        "request_id": "cli-unknown-1",
        "payload": {}
    }));

    assert_eq!(events.len(), 1);
    assert_protocol_error(&events[0], json!("cli-unknown-1"));
    assert_eq!(events[0]["command"], "unknown.command");
}

#[test]
fn helper_binary_emits_structured_invalid_json_error() {
    let events = run_helper_lines("{\n");

    assert_eq!(events.len(), 1);
    assert_protocol_error(&events[0], json!("protocol-invalid-request-id"));
    assert_eq!(events[0]["command"], Value::Null);
}

#[test]
fn helper_binary_exits_nonzero_when_stdout_emission_fails() {
    for input in [
        "{\"command\":\"service.hello\",\"request_id\":\"closed-stdout\",\"payload\":{}}\n",
        "{\n",
    ] {
        let output = run_helper_with_closed_stdout(input);

        assert!(
            !output.status.success(),
            "closed stdout must fail the process for input {input:?}; stderr={}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

#[test]
fn helper_binary_preserves_two_request_ids() {
    let events = run_helper_lines(
        "{\"command\":\"service.hello\",\"request_id\":\"cli-first-1\",\"payload\":{}}\n\
         {\"command\":\"unknown.command\",\"request_id\":\"cli-second-1\",\"payload\":{}}\n",
    );

    assert_eq!(events.len(), 2);
    assert_eq!(events[0]["request_id"], "cli-first-1");
    assert_protocol_error(&events[1], json!("cli-second-1"));
}

#[test]
fn query_execute_memory_payload_preserves_explicit_columns() {
    let events = run_helper(json!({
        "command": "query.execute",
        "request_id": "query-columns-1",
        "payload": {
            "rows": [],
            "columns": ["id", "name"]
        }
    }));

    let result = events
        .iter()
        .find(|event| event.get("event") == Some(&json!("result")))
        .unwrap();
    assert_eq!(result["command"], "query.execute");
    assert_eq!(result["success"], true);
    assert_eq!(result["rows"], json!([]));
    assert_eq!(result["columns"], json!(["id", "name"]));
}

#[test]
fn helper_binary_frame_chunks_expanded_utf8_plan_under_wire_cap() {
    let column_name = "열".repeat(220_000);
    let request = json!({
        "command": "plan",
        "request_id": "cli-large-frame-1",
        "payload": {
            "source_engine": "mysql",
            "target_engine": "postgresql",
            "schema": {
                "tables": [{
                    "name": "large_names",
                    "columns": [{
                        "name": column_name,
                        "type": "int(11) auto_increment",
                        "nullable": false,
                        "primary_key": true
                    }]
                }]
            }
        }
    });
    let input = format!("{request}\n");
    assert!(input.as_bytes().len() < 1_048_576);

    let output = run_helper_output(&input);
    let frames = output
        .split_inclusive(|byte| *byte == b'\n')
        .filter(|frame| !frame.is_empty())
        .collect::<Vec<_>>();

    assert!(frames.len() > 1);
    assert!(frames.iter().all(|frame| frame.len() <= 1_048_576));
    assert!(frames.iter().all(|frame| std::str::from_utf8(frame).is_ok()));
    assert!(frames.iter().any(|frame| {
        serde_json::from_slice::<Value>(frame).unwrap()["event"] == "payload_chunk"
    }));
}

#[test]
fn helper_binary_rejects_oversized_frame_and_processes_next_request() {
    let mut input = "x".repeat(1_048_576);
    input.push_str("x\n");
    input.push_str(
        "{\"command\":\"service.hello\",\"request_id\":\"after-large\",\"payload\":{}}\n",
    );

    let events = run_helper_lines(&input);

    assert_eq!(events.len(), 2);
    assert_eq!(events[0]["code"], "jsonl_frame_too_large");
    assert_eq!(events[0]["command"], Value::Null);
    assert_eq!(events[1]["request_id"], "after-large");
}

#[test]
fn helper_binary_rejects_unterminated_jsonl_frame() {
    let events = run_helper_lines(
        "{\"command\":\"service.hello\",\"request_id\":\"unterminated\",\"payload\":{}}",
    );

    assert_eq!(events.len(), 1);
    assert_eq!(events[0]["code"], "jsonl_frame_missing_newline");
    assert_eq!(events[0]["command"], Value::Null);
}

#[test]
fn helper_binary_rejects_invalid_request_ids_without_null_envelopes() {
    for input in [
        "{\"command\":\"service.hello\",\"payload\":{}}\n",
        "{\"command\":\"service.hello\",\"request_id\":null,\"payload\":{}}\n",
        "{\"command\":\"service.hello\",\"request_id\":7,\"payload\":{}}\n",
        "{\"command\":\"service.hello\",\"request_id\":\"\",\"payload\":{}}\n",
    ] {
        let events = run_helper_lines(input);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0]["event"], "error");
        assert!(matches!(events[0]["request_id"].as_str(), Some(value) if !value.is_empty()));
        assert_ne!(events[0]["request_id"], Value::Null);
    }
}
