use serde_json::{json, Value};
use std::io::Write;
use std::process::{Command, Stdio};

fn helper_binary() -> String {
    std::env::var("CARGO_BIN_EXE_tunnelforge-core").unwrap_or_else(|_| {
        let mut path = std::env::current_exe().unwrap();
        path.pop();
        if path.ends_with("deps") {
            path.pop();
        }
        path.push(if cfg!(windows) {
            "tunnelforge-core.exe"
        } else {
            "tunnelforge-core"
        });
        path.to_string_lossy().to_string()
    })
}

fn run_helper(request: Value) -> Vec<Value> {
    run_helper_lines(&format!("{request}\n"))
}

fn run_helper_lines(input: &str) -> Vec<Value> {
    let mut child = Command::new(helper_binary())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    {
        let stdin = child.stdin.as_mut().unwrap();
        write!(stdin, "{input}").unwrap();
    }
    let output = child.wait_with_output().unwrap();
    assert!(output.status.success());
    String::from_utf8(output.stdout)
        .unwrap()
        .lines()
        .map(|line| serde_json::from_str::<Value>(line).unwrap())
        .collect()
}

#[test]
fn helper_binary_accepts_jsonl_and_emits_result() {
    let events = run_helper(json!({
        "command": "plan",
        "request_id": "cli-1",
        "payload": {
            "source_engine": "mysql",
            "target_engine": "postgresql",
            "schema": {
                "tables": [{
                    "name": "users",
                    "columns": [{
                        "name": "id",
                        "type": "int(11) auto_increment",
                        "nullable": false,
                        "primary_key": true
                    }]
                }]
            }
        }
    }));

    let result = events
        .iter()
        .find(|event| event.get("event") == Some(&json!("result")))
        .unwrap();
    assert_eq!(result["request_id"], "cli-1");
    assert_eq!(result["command"], "plan");
    assert_eq!(result["success"], true);
    assert_eq!(
        result["plan"]["ddl"][0],
        "CREATE TABLE \"users\" (\n  \"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  PRIMARY KEY (\"id\")\n);"
    );
}

fn assert_protocol_error(event: &Value, request_id: Value) {
    assert_eq!(event["event"], "error");
    assert_eq!(event["request_id"], request_id);
    assert!(matches!(event["code"].as_str(), Some(value) if !value.is_empty()));
    assert!(matches!(event["message"].as_str(), Some(value) if !value.is_empty()));
}

#[test]
fn helper_binary_negotiates_process_contract() {
    let events = run_helper(json!({
        "command": "service.hello",
        "request_id": "cli-hello-1",
        "payload": {}
    }));

    assert_eq!(events.len(), 1);
    let result = &events[0];
    assert_eq!(result["request_id"], "cli-hello-1");
    assert_eq!(result["protocol_version"], 1);
    assert_eq!(result["process_version"], 1);
    assert_eq!(
        result["process_capabilities"],
        json!([
            "request.deadline",
            "request.strict_id",
            "process.generation",
            "mutation.outcome_indeterminate"
        ])
    );
    assert_eq!(result["max_jsonl_frame_bytes"], 1_048_576);
}

#[test]
fn helper_binary_emits_structured_unknown_command_error() {
    let events = run_helper(json!({
        "command": "unknown.command",
        "request_id": "cli-unknown-1",
        "payload": {}
    }));

    assert_eq!(events.len(), 1);
    assert_protocol_error(&events[0], json!("cli-unknown-1"));
}

#[test]
fn helper_binary_emits_structured_invalid_json_error() {
    let events = run_helper_lines("{\n");

    assert_eq!(events.len(), 1);
    assert_protocol_error(&events[0], Value::Null);
}

#[test]
fn helper_binary_preserves_two_request_ids() {
    let events = run_helper_lines(
        "{\"command\":\"service.hello\",\"request_id\":\"cli-first-1\",\"payload\":{}}\n\
         {\"command\":\"unknown.command\",\"request_id\":\"cli-second-1\",\"payload\":{}}\n",
    );

    assert_eq!(events.len(), 2);
    assert_eq!(events[0]["request_id"], "cli-first-1");
    assert_protocol_error(&events[1], json!("cli-second-1"));
}

#[test]
fn query_execute_memory_payload_preserves_explicit_columns() {
    let events = run_helper(json!({
        "command": "query.execute",
        "request_id": "query-columns-1",
        "payload": {
            "rows": [],
            "columns": ["id", "name"]
        }
    }));

    let result = events
        .iter()
        .find(|event| event.get("event") == Some(&json!("result")))
        .unwrap();
    assert_eq!(result["command"], "query.execute");
    assert_eq!(result["success"], true);
    assert_eq!(result["rows"], json!([]));
    assert_eq!(result["columns"], json!(["id", "name"]));
}
