use serde_json::{json, Value};
use std::io::Write;
use std::process::{Command, Stdio};

fn helper_binary() -> String {
    std::env::var("CARGO_BIN_EXE_tunnelforge-core").unwrap_or_else(|_| {
        let mut path = std::env::current_exe().unwrap();
        path.pop();
        if path.ends_with("deps") {
            path.pop();
        }
        path.push(if cfg!(windows) {
            "tunnelforge-core.exe"
        } else {
            "tunnelforge-core"
        });
        path.to_string_lossy().to_string()
    })
}

fn run_helper(request: Value) -> Vec<Value> {
    let mut child = Command::new(helper_binary())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    {
        let stdin = child.stdin.as_mut().unwrap();
        writeln!(stdin, "{request}").unwrap();
    }
    let output = child.wait_with_output().unwrap();
    assert!(output.status.success());
    String::from_utf8(output.stdout)
        .unwrap()
        .lines()
        .map(|line| serde_json::from_str::<Value>(line).unwrap())
        .collect()
}

#[test]
fn helper_binary_accepts_jsonl_and_emits_result() {
    let events = run_helper(json!({
        "command": "plan",
        "request_id": "cli-1",
        "payload": {
            "source_engine": "mysql",
            "target_engine": "postgresql",
            "schema": {
                "tables": [{
                    "name": "users",
                    "columns": [{
                        "name": "id",
                        "type": "int(11) auto_increment",
                        "nullable": false,
                        "primary_key": true
                    }]
                }]
            }
        }
    }));

    let result = events
        .iter()
        .find(|event| event.get("event") == Some(&json!("result")))
        .unwrap();
    assert_eq!(result["request_id"], "cli-1");
    assert_eq!(result["command"], "plan");
    assert_eq!(result["success"], true);
    assert_eq!(
        result["plan"]["ddl"][0],
        "CREATE TABLE \"users\" (\n  \"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  PRIMARY KEY (\"id\")\n);"
    );
}
