use migration_core::{handle_request, Endpoint, Request};
use mysql::prelude::Queryable;
use serde_json::{json, Value};
static LIVE_SCHEMA_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

fn endpoint(engine: &str) -> Option<Endpoint> {
    let prefix = if engine == "mysql" { "TF_MYSQL" } else { "TF_POSTGRES" };
    Some(Endpoint {
        engine: engine.into(), host: std::env::var(format!("{prefix}_HOST")).ok()?,
        port: if engine == "mysql" { 3306 } else { 5432 },
        user: std::env::var(format!("{prefix}_USER")).unwrap_or_else(|_| if engine == "mysql" { "root".into() } else { "postgres".into() }),
        password: std::env::var(format!("{prefix}_PASSWORD")).unwrap_or_else(|_| "tf_local_test".into()),
        database: std::env::var(format!("{prefix}_DATABASE")).unwrap_or_else(|_| "tf_test".into()), schema: None,
    })
}
fn unique_name() -> String {
    format!("tf_fidelity_{}", std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos())
}
fn run(command: &str, payload: Value) -> Value {
    let events = handle_request(Request { command: command.into(), request_id: None, payload });
    assert!(!events.iter().any(|e| e["event"] == "error"), "{events:#?}");
    events.into_iter().find(|e| e["event"] == "result").unwrap()
}
fn restore(source: &Endpoint, target: &Endpoint) {
    let dir = std::env::temp_dir().join(unique_name());
    let result = run("dump.run", json!({"source":source,"tables":["sample"],"output_dir":dir,"data_format":"tsv","compression":"zstd","threads":1}));
    assert_eq!(result["success"], true);
    let result = run("dump.import", json!({"target":target,"input_dir":dir,"mode":"replace","threads":1}));
    assert_eq!(result["success"], true);
    std::fs::remove_dir_all(dir).unwrap();
}
#[test]
fn postgres_defaults_arrays_identity_survive_restore_into_another_schema() {
    let _guard = LIVE_SCHEMA_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let Some(mut source) = endpoint("postgresql") else { return; };
    let mut client = postgres::Config::new().host(&source.host).user(&source.user).password(&source.password).dbname(&source.database).connect(postgres::NoTls).unwrap();
    let from = unique_name(); let to = format!("{from}_dst");
    client.batch_execute(&format!("CREATE SCHEMA {from}; CREATE SCHEMA {to}; SET search_path TO {from}")).unwrap();
    source.schema = Some(from.clone());
    let mut target = source.clone(); target.schema = Some(to.clone());
    client.batch_execute("CREATE TABLE sample (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, stamp timestamp(3) DEFAULT now(), active boolean DEFAULT true, token uuid DEFAULT gen_random_uuid(), doc jsonb DEFAULT '{\"a::b\":1}'::jsonb, items integer[] DEFAULT ARRAY[1,2], blank text DEFAULT '', marker text DEFAULT 'a::b', label text, UNIQUE(label, marker)); INSERT INTO sample(label) VALUES ('original')").unwrap();
    restore(&source, &target);
    client.batch_execute(&format!("SET search_path TO {to}; INSERT INTO sample(label) VALUES ('future')")).unwrap();
    let row = client.query_one("SELECT id, active, doc::text, items::text, blank, marker, token IS NOT NULL, stamp IS NOT NULL FROM sample WHERE label='future'", &[]).unwrap();
    assert_eq!(row.get::<_,i64>(0), 2);
    assert!(row.get::<_,bool>(1));
    assert_eq!(row.get::<_,String>(2), "{\"a::b\": 1}");
    assert_eq!(row.get::<_,String>(3), "{1,2}");
    assert_eq!(row.get::<_,String>(4), ""); assert_eq!(row.get::<_,String>(5), "a::b");
    assert!(row.get::<_,bool>(6)); assert!(row.get::<_,bool>(7));
    assert!(client.batch_execute("INSERT INTO sample(label) VALUES ('future')").is_err());
    let precision: i32 = client.query_one("SELECT datetime_precision FROM information_schema.columns WHERE table_schema=$1 AND table_name='sample' AND column_name='stamp'", &[&to]).unwrap().get(0);
    assert_eq!(precision, 3);
    client.batch_execute(&format!("DROP SCHEMA {from} CASCADE; DROP SCHEMA {to} CASCADE")).unwrap();
}
#[test]
fn mysql_defaults_on_update_and_unique_survive_restore_into_another_database() {
    let _guard = LIVE_SCHEMA_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let Some(mut source) = endpoint("mysql") else { return; };
    let opts = mysql::OptsBuilder::new().ip_or_hostname(Some(source.host.clone())).user(Some(source.user.clone())).pass(Some(source.password.clone()));
    let mut conn = mysql::Pool::new(opts).unwrap().get_conn().unwrap();
    let from = unique_name(); let to = format!("{from}_dst");
    conn.query_drop(format!("CREATE DATABASE {from}")).unwrap(); conn.query_drop(format!("CREATE DATABASE {to}")).unwrap();
    conn.query_drop(format!("USE {from}")).unwrap(); source.database=from.clone(); let mut target=source.clone(); target.database=to.clone();
    conn.query_drop("CREATE TABLE sample (id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY, stamp timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), level enum('LOW','HIGH') NOT NULL DEFAULT 'LOW', blank varchar(40) NOT NULL DEFAULT '', marker varchar(40) NOT NULL DEFAULT 'null', payload varbinary(8), label varchar(40), UNIQUE(label, marker), UNIQUE KEY uq_prefix(label(5), marker(10)))").unwrap();
    conn.query_drop("INSERT INTO sample(label,payload,stamp) VALUES ('original',X'00ff0102','2001-01-01 00:00:00.123456')").unwrap();
    restore(&source,&target);
    conn.query_drop(format!("USE {to}")).unwrap();
    conn.query_drop("INSERT INTO sample(label) VALUES ('future')").unwrap();
    let row: (u64,String,String,String)=conn.query_first("SELECT id,level,blank,marker FROM sample WHERE label='future'").unwrap().unwrap();
    assert_eq!(row,(2,"LOW".into(),"".into(),"null".into()));
    assert!(conn.query_drop("INSERT INTO sample(label) VALUES ('future')").is_err());
    let before: String=conn.query_first("SELECT CAST(stamp AS CHAR) FROM sample WHERE id=1").unwrap().unwrap();
    assert_eq!(before,"2001-01-01 00:00:00.123456");
    conn.query_drop("UPDATE sample SET label='updated' WHERE id=1").unwrap();
    let after: String=conn.query_first("SELECT CAST(stamp AS CHAR) FROM sample WHERE id=1").unwrap().unwrap();
    assert_ne!(before,after);
    let prefixes: Vec<Option<u32>> = conn.query("SELECT SUB_PART FROM information_schema.statistics WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sample' AND INDEX_NAME='uq_prefix' ORDER BY SEQ_IN_INDEX").unwrap();
    assert_eq!(prefixes,vec![Some(5),Some(10)]);
    let binary: String=conn.query_first("SELECT HEX(payload) FROM sample WHERE id=1").unwrap().unwrap(); assert_eq!(binary,"00FF0102");
    conn.query_drop(format!("DROP DATABASE {from}")).unwrap(); conn.query_drop(format!("DROP DATABASE {to}")).unwrap();
}

#[test]
fn mysql_replace_preserves_target_only_child_referencing_secondary_unique_key() {
    let _guard = LIVE_SCHEMA_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let Some(mut endpoint) = endpoint("mysql") else { return; };
    let opts = mysql::OptsBuilder::new().ip_or_hostname(Some(endpoint.host.clone())).user(Some(endpoint.user.clone())).pass(Some(endpoint.password.clone()));
    let mut conn = mysql::Pool::new(opts).unwrap().get_conn().unwrap();
    let database=unique_name(); conn.query_drop(format!("CREATE DATABASE {database}")).unwrap(); conn.query_drop(format!("USE {database}")).unwrap(); endpoint.database=database.clone();
    conn.query_drop("CREATE TABLE sample (id int NOT NULL AUTO_INCREMENT PRIMARY KEY, code varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, previous_code varchar(50) COLLATE utf8mb4_unicode_ci, UNIQUE KEY uq_code(code), FOREIGN KEY(previous_code) REFERENCES sample(code))").unwrap();
    conn.query_drop("CREATE TABLE target_only_child (id int PRIMARY KEY, parent_code varchar(50) COLLATE utf8mb4_unicode_ci, FOREIGN KEY(parent_code) REFERENCES sample(code))").unwrap();
    conn.query_drop("INSERT INTO sample(code) VALUES ('a'),('b')").unwrap(); conn.query_drop("INSERT INTO target_only_child VALUES (1,'a')").unwrap();
    restore(&endpoint,&endpoint);
    let count: u64=conn.query_first("SELECT COUNT(*) FROM target_only_child WHERE parent_code='a'").unwrap().unwrap(); assert_eq!(count,1);
    assert!(conn.query_drop("INSERT INTO sample(code) VALUES ('a')").is_err());
    assert!(conn.query_drop("INSERT INTO target_only_child VALUES (2,'missing')").is_err());
    conn.query_drop("INSERT INTO sample(code,previous_code) VALUES ('c','b')").unwrap();
    conn.query_drop(format!("DROP DATABASE {database}")).unwrap();
}

fn assert_export_rejected(endpoint: &Endpoint, marker: &str) {
    let dir=std::env::temp_dir().join(unique_name());
    let events=handle_request(Request{command:"dump.run".into(),request_id:None,payload:json!({"source":endpoint,"tables":["sample"],"output_dir":dir,"threads":1})});
    assert!(events.iter().any(|e| e["event"]=="error" && e["message"].as_str().unwrap_or("").contains(marker)), "{events:#?}");
    assert!(!dir.join("manifest.json").exists(), "unsupported schema must not produce a success manifest");
}
#[test]
fn unsupported_schema_features_are_rejected_before_export() {
    let _guard = LIVE_SCHEMA_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    if let Some(mut endpoint)=endpoint("mysql") {
        let opts=mysql::OptsBuilder::new().ip_or_hostname(Some(endpoint.host.clone())).user(Some(endpoint.user.clone())).pass(Some(endpoint.password.clone()));
        let mut conn=mysql::Pool::new(opts).unwrap().get_conn().unwrap(); let database=unique_name();
        conn.query_drop(format!("CREATE DATABASE {database}")).unwrap(); conn.query_drop(format!("USE {database}")).unwrap(); endpoint.database=database.clone();
        for (ddl,marker) in [
            ("CREATE TABLE sample (id int, doubled int GENERATED ALWAYS AS (id*2) STORED)","generated_column:sample:doubled"),
            ("CREATE TABLE sample (id int, token varchar(40) DEFAULT (lower(uuid())))","unsupported_default:sample:token"),
        ] {
            conn.query_drop(ddl).unwrap(); assert_export_rejected(&endpoint,marker); conn.query_drop("DROP TABLE sample").unwrap();
        }
        conn.query_drop(format!("DROP DATABASE {database}")).unwrap();
    }
    if let Some(mut endpoint)=endpoint("postgresql") {
        let mut client=postgres::Config::new().host(&endpoint.host).user(&endpoint.user).password(&endpoint.password).dbname(&endpoint.database).connect(postgres::NoTls).unwrap();
        let schema=unique_name(); client.batch_execute(&format!("CREATE SCHEMA {schema}; SET search_path TO {schema}")).unwrap(); endpoint.schema=Some(schema.clone());
        for (ddl,marker) in [
            ("CREATE TABLE sample (id int, doubled int GENERATED ALWAYS AS (id*2) STORED)","generated_column:sample:doubled"),
            ("CREATE TABLE sample (id int CONSTRAINT positive_id CHECK(id>0))","check_constraint:sample:positive_id"),
            ("CREATE TABLE sample (id int, token text DEFAULT lower('X'))","unsupported_default:sample:token"),
            ("CREATE TABLE sample (id bigint GENERATED ALWAYS AS IDENTITY)","unsupported_default:sample:id"),
            ("CREATE TABLE sample (id bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 2))","unsupported_default:sample:id"),
            ("CREATE TABLE sample (label text); CREATE UNIQUE INDEX filtered_unique ON sample(label) WHERE label IS NOT NULL","unsupported_index:sample:filtered_unique"),
        ] {
            client.batch_execute(ddl).unwrap(); assert_export_rejected(&endpoint,marker); client.batch_execute("DROP TABLE sample").unwrap();
        }
        client.batch_execute(&format!("DROP SCHEMA {schema} CASCADE")).unwrap();
    }
}

#[test]
fn legacy_mysql_manifests_preserve_literal_string_defaults_after_restore() {
    let _guard = LIVE_SCHEMA_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let Some(mut endpoint) = endpoint("mysql") else { return; };
    let opts = mysql::OptsBuilder::new().ip_or_hostname(Some(endpoint.host.clone())).user(Some(endpoint.user.clone())).pass(Some(endpoint.password.clone()))
        .pool_opts(mysql::PoolOpts::default().with_constraints(mysql::PoolConstraints::new(0,1).unwrap()));
    let mut conn = mysql::Pool::new(opts).unwrap().get_conn().unwrap();
    let database = unique_name();
    conn.query_drop(format!("CREATE DATABASE {database}")).unwrap(); conn.query_drop(format!("USE {database}")).unwrap();
    endpoint.database = database.clone();
    let defaults = ["", "null", "TRUE", "FALSE", "CURRENT_TIMESTAMP", "NOW()", "O'Reilly", "'quoted'", "  padded  ", "0012", "a::b", "a\\b"];
    for version in [1,2] {
        let mut columns: Vec<_> = defaults.iter().enumerate().map(|(i,value)| json!({"name":format!("value_{i}"),"type":"varchar(80)","default":value,"nullable":false})).collect();
        columns.extend([
            json!({"name":"enum_flag","type":"enum('TRUE','FALSE')","default":"TRUE","nullable":false}),
            json!({"name":"set_flags","type":"set('TRUE','null')","default":"TRUE,null","nullable":false}),
            json!({"name":"quantity","type":"int","default":"7","nullable":false}),
            json!({"name":"created","type":"timestamp(3)","default":"CURRENT_TIMESTAMP(3)","nullable":false}),
        ]);
        let dir = std::env::temp_dir().join(unique_name()); std::fs::create_dir_all(&dir).unwrap();
        let manifest = json!({"format":"tunnelforge-dump","format_version":version,"source_engine":"mysql","database":"legacy_source","schema":{"tables":[{"name":"sample","columns":columns}]},"chunk_size":100,"created_unix_seconds":1,"tables":[{"name":"sample","path":"sample","rows":0,"chunks":0}]});
        std::fs::write(dir.join("_tunnelforge_dump.json"),serde_json::to_vec(&manifest).unwrap()).unwrap();
        let result = run("dump.import",json!({"target":endpoint,"input_dir":dir,"mode":"replace","threads":1})); assert_eq!(result["success"],true);
        conn.query_drop("INSERT INTO sample () VALUES ()").unwrap();
        let row: mysql::Row = conn.query_first("SELECT * FROM sample").unwrap().unwrap();
        for (i,value) in defaults.iter().enumerate() { assert_eq!(row.get::<String,_>(i).as_deref(),Some(*value),"v{version} column {i}"); }
        assert_eq!(row.get::<String,_>("enum_flag").as_deref(),Some("TRUE"));
        assert_eq!(row.get::<String,_>("set_flags").as_deref(),Some("TRUE,null"));
        assert_eq!(row.get::<i32,_>("quantity"),Some(7));
        assert!(!matches!(row.as_ref(defaults.len()+3),Some(mysql::Value::NULL)));
        std::fs::remove_dir_all(dir).unwrap();
    }
    conn.query_drop(format!("DROP DATABASE {database}")).unwrap();
}

#[test]
fn mysql_checks_uuid_visibility_comments_and_allocator_survive_restore() {
    let _guard = LIVE_SCHEMA_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let Some(mut source) = endpoint("mysql") else { return; };
    let opts = mysql::OptsBuilder::new().ip_or_hostname(Some(source.host.clone())).user(Some(source.user.clone())).pass(Some(source.password.clone()))
        .pool_opts(mysql::PoolOpts::default().with_constraints(mysql::PoolConstraints::new(0,1).unwrap()));
    let mut conn=mysql::Pool::new(opts).unwrap().get_conn().unwrap();
    let from=unique_name(); let to=format!("{from}_dst");
    conn.query_drop(format!("CREATE DATABASE {from}")).unwrap(); conn.query_drop(format!("CREATE DATABASE {to}")).unwrap(); conn.query_drop(format!("USE {from}")).unwrap();
    source.database=from.clone(); let mut target=source.clone(); target.database=to.clone();
    conn.query_drop("CREATE TABLE sample(id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY, token varchar(36) DEFAULT (uuid()), quantity int NOT NULL DEFAULT 1 COMMENT 'column ''note'' 한글', label varchar(80), CONSTRAINT positive_quantity CHECK(quantity>0) ENFORCED, CONSTRAINT optional_limit CHECK(quantity<10) NOT ENFORCED, INDEX hidden_label(label) INVISIBLE) AUTO_INCREMENT=9001 COMMENT='table ''note'' 한글'").unwrap();
    conn.query_drop("INSERT INTO sample(id,label) VALUES(1,'original')").unwrap();
    let cached:u64=conn.query_first("SELECT AUTO_INCREMENT FROM information_schema.tables WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sample'").unwrap().unwrap(); assert_eq!(cached,9001);
    conn.query_drop("INSERT INTO sample(id,label) VALUES(12000,'allocated')").unwrap();
    conn.query_drop("DELETE FROM sample WHERE id=12000").unwrap();
    restore(&source,&target);
    conn.query_drop(format!("USE {to}")).unwrap();
    conn.query_drop("INSERT INTO sample(quantity,label) VALUES(20,'future')").unwrap();
    let future_id:u64=conn.query_first("SELECT id FROM sample WHERE label='future'").unwrap().unwrap(); assert_eq!(future_id,12001);
    let uuid_count:u64=conn.query_first("SELECT COUNT(DISTINCT token) FROM sample WHERE LENGTH(token)=36").unwrap().unwrap(); assert_eq!(uuid_count,2);
    assert!(conn.query_drop("INSERT INTO sample(quantity) VALUES(-1)").is_err());
    let visible:String=conn.query_first("SELECT IS_VISIBLE FROM information_schema.statistics WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sample' AND INDEX_NAME='hidden_label'").unwrap().unwrap(); assert_eq!(visible,"NO");
    let table_comment:String=conn.query_first("SELECT TABLE_COMMENT FROM information_schema.tables WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sample'").unwrap().unwrap(); assert_eq!(table_comment,"table 'note' 한글");
    let column_comment:String=conn.query_first("SELECT COLUMN_COMMENT FROM information_schema.columns WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sample' AND COLUMN_NAME='quantity'").unwrap().unwrap(); assert_eq!(column_comment,"column 'note' 한글");
    let enforced:Vec<(String,String)>=conn.query("SELECT CONSTRAINT_NAME,ENFORCED FROM information_schema.table_constraints WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sample' AND CONSTRAINT_TYPE='CHECK' ORDER BY CONSTRAINT_NAME").unwrap();
    assert_eq!(enforced,vec![("optional_limit".into(),"NO".into()),("positive_quantity".into(),"YES".into())]);
    conn.query_drop(format!("DROP DATABASE {from}")).unwrap(); conn.query_drop(format!("DROP DATABASE {to}")).unwrap();
}

#[test]
fn postgres_quoted_identity_table_restores_sequence_to_correct_relation() {
    let _guard=LIVE_SCHEMA_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let Some(mut endpoint)=endpoint("postgresql") else { return; };
    let mut client=postgres::Config::new().host(&endpoint.host).user(&endpoint.user).password(&endpoint.password).dbname(&endpoint.database).connect(postgres::NoTls).unwrap();
    let schema=unique_name(); client.batch_execute(&format!("CREATE SCHEMA {schema}; SET search_path TO {schema}")).unwrap(); endpoint.schema=Some(schema.clone());
    client.batch_execute("CREATE TABLE \"Mixed.Table\" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY); INSERT INTO \"Mixed.Table\" DEFAULT VALUES").unwrap();
    let dir=std::env::temp_dir().join(unique_name());
    run("dump.run",json!({"source":endpoint,"tables":["Mixed.Table"],"output_dir":dir,"threads":1}));
    run("dump.import",json!({"target":endpoint,"input_dir":dir,"mode":"replace","threads":1}));
    let id:i64=client.query_one("INSERT INTO \"Mixed.Table\" DEFAULT VALUES RETURNING id",&[]).unwrap().get(0); assert_eq!(id,2);
    std::fs::remove_dir_all(dir).unwrap(); client.batch_execute(&format!("DROP SCHEMA {schema} CASCADE")).unwrap();
}
